version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=111111
      - POSTGRES_DB=django
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=django
      - DATABASE_USER=root
      - DATABASE_PASSWORD=111111
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - ALLOWED_HOSTS=*
    depends_on:
      - postgres